### ISSUE TITLE
実行時エラーが起きてしまいます。

### ISSUE THREAD

**Issue by fujas** [techlabxe/vk_raytracing_book_1#1]
Vulkan Raytracing Programming Vol.1 を拝見させていただいています。
こちらのサンプル 01_HelloTriangle を実行しようとしたのですが、vkCreateRayTracingPipelinesKHR() の呼び出しで例外が発生して落ちてしまいます。
何か情報有りますでしょうか？

![キャプチャ](https://user-images.githubusercontent.com/50135168/152673693-a25356c3-b037-4970-9894-a185c26ac0ed.JPG)

DELL ノート G5, RTX2060, Windows10, VS2019, VulkanSDK 1.2.198.1という構成です。
ちなみに、vkXxxxHuaweiという定義でコンパイルエラーが起きるので、エラー個所はコメントにしています。

環境の問題かと思いましたが、
https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR
は私の環境でも動作しています。

どうぞよろしくお願いいたします。

**Comment by techlabxe** [comment]
お問い合わせありがとうございます。
他の Vulkan Raytracing サンプルは動いているとのことですので、根本の環境は問題なさそうですね。

念のための確認ですが、シェーダーファイルを compileShader.bat にて、コンパイルはされている状態でしょうか？
本リポジトリに含まれるシェーダーはGLSLのままで、コンパイルしたものを付属させていないため、本バッチにてコンパイルをお願いしております。
（わかりにくくて申し訳ありません）

**Comment by fujas** [comment]
素早いご回答ありがとうございます。
無事実行できました。
基本的なところですみません。。

**Comment by techlabxe** [comment]
無事実行出来たとのことで、安心しました。
他のサンプルも同様に事前にシェーダーのコンパイルが必要となっていますので、よろしくお願い致します。
